/* global process, console */
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const sourcePath = resolve(root, 'src/tokens/source.json');
const cssPath = resolve(root, 'src/tokens/semantic.css');
const tsPath = resolve(root, 'src/tokens/generated.ts');
const source = JSON.parse(await readFile(sourcePath, 'utf8'));

const themeLines = (theme) => {
  const value = source.color[theme];
  const lines = [
    `  --core-color-surface-page: ${value.surface.page};`,
    `  --core-color-surface-default: ${value.surface.default};`,
    `  --core-color-surface-subtle: ${value.surface.subtle};`,
    `  --core-color-surface-raised: ${value.surface.raised};`,
    `  --core-color-border-default: ${value.border.default};`,
    `  --core-color-border-strong: ${value.border.strong};`,
    `  --core-color-text-primary: ${value.text.primary};`,
    `  --core-color-text-secondary: ${value.text.secondary};`,
    `  --core-color-text-muted: ${value.text.muted};`,
    `  --core-color-text-disabled: ${value.text.disabled};`,
    `  --core-color-text-on-primary: ${value.text.onPrimary};`,
    `  --core-color-text-on-danger: ${value.text.onDanger};`,
  ];
  for (const [name, status] of Object.entries(value.status)) {
    lines.push(`  --core-color-${name}: ${status.foreground};`, `  --core-color-${name}-surface: ${status.surface};`);
  }
  return lines.join('\n');
};

const css = `/* Generated by scripts/generate-tokens.mjs from src/tokens/source.json. Do not edit. */
:root {
  --core-font-family-latin: ${source.font.latin};
  --core-font-family-arabic: ${source.font.arabic};
  --core-font-family-mono: ${source.font.mono};
  --core-font-family: var(--core-font-family-latin);
  --core-display-font-family: ${source.font.display};
  --core-color-brand-cyan: ${source.color.brand.cyan};
  --core-color-brand-blue: ${source.color.brand.blue};
  --core-color-brand-violet: ${source.color.brand.violet};
  --core-color-action-primary: ${source.color.brand.blue};
  --core-color-action-primary-hover: color-mix(in srgb, var(--core-color-action-primary) 84%, black);
  --core-color-action-danger: ${source.color.light.status.danger.foreground};
  --core-color-action-danger-hover: color-mix(in srgb, var(--core-color-action-danger) 84%, black);
  --core-color-focus: ${source.focus.color};
${themeLines('light')}
  --core-shadow-raised: ${source.shadow.raised};
${Object.entries(source.radius).map(([k,v]) => `  --core-radius-${k}: ${v};`).join('\n')}
${Object.entries(source.space).map(([k,v]) => `  --core-space-${k}: ${v};`).join('\n')}
${Object.entries(source.control).map(([k,v]) => `  --core-control-${k}: ${v};`).join('\n')}
  --core-focus-width: ${source.focus.width};
  --core-focus-offset: ${source.focus.offset};
}

.core-root[lang='fa'], .core-root[lang='ar'], [lang='fa'] .core-root, [lang='ar'] .core-root {
  --core-font-family: var(--core-font-family-arabic);
}

[data-theme='dark'] {
${themeLines('dark')}
  --core-shadow-raised: ${source.shadow.raisedDark};
}
`;

const ts = `/* Generated by scripts/generate-tokens.mjs from source.json. Do not edit. */\nexport const coreTokens = ${JSON.stringify(source, null, 2)} as const;\nexport type CoreTokens = typeof coreTokens;\n`;
const check = process.argv.includes('--check');
if (check) {
  const [currentCss, currentTs] = await Promise.all([readFile(cssPath, 'utf8'), readFile(tsPath, 'utf8')]);
  if (currentCss !== css || currentTs !== ts) { console.error('Generated token outputs are stale. Run pnpm tokens:generate.'); process.exit(1); }
} else {
  await Promise.all([writeFile(cssPath, css), writeFile(tsPath, ts)]);
}
